### ISSUE TITLE
[FR] in-app browser view for repo module's xda/github/etc links

### ISSUE THREAD

**Issue by DB9-max** [MRepoApp/MRepo#105]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of MRepo. / 这个建议不会背离 MRepo 的初衷。

### Enhancement propose / 改进目的

It's frustrating to leave the app everytime just to go to another app to view more details, dl, starring, following and whatnot

### Solution / 解决方案

In-app browser view / custom tab solution

### Additional info / 额外信息

Would make Mrepo more joyful to use

**Comment by SanmerDev** [comment]
Not planned
