### ISSUE TITLE
[FR] Distinguish modules not only by id but also by author

### ISSUE THREAD

**Issue by Mark-Joy** [MRepoApp/MRepo#106]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of MRepo. / 这个建议不会背离 MRepo 的初衷。

### Enhancement propose / 改进目的

I have manually installed (install from storage) a module named [ADB Root by evdenis](https://github.com/evdenis/adb_root) (not on any repos).
It was undistinguished with [adb root by weishu](https://github.com/tiann/adb_root), the one that is on the repo and has greater version code. They both have id as adb_root

In modules tab, I can see update button available for [ADB Root by evdenis]
When I click update, MRepo overwrites [ADB Root by evdenis] with [adb root by weishu]

This would cause trouble if user was not awared of the situation.

![evdenis](https://github.com/ya0211/MRepo/assets/22109528/8da28efe-84bf-4a39-92d6-116ce2df64e5)
![weishu](https://github.com/ya0211/MRepo/assets/22109528/f786c0a8-b25b-4855-80ca-f36ec8cfbc7e)

### Solution / 解决方案

To avoid the above situation, can we distinguish modules not only by id but also by author?

Thank you.

**Comment by SanmerDev** [comment]
It cannot be processed, because id is the unique identifier of a module. No matter where it is, id is relied on to distinguish different modules.

But I will add a check for author so that it will not prompt wrong update notification.
