### ISSUE TITLE
[BUG] White background on first launch with dark system theme enabled

### ISSUE THREAD

**Issue by Daviteusz** [MRepoApp/MRepo#107]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of MRepo. / 我正在使用 MRepo 的最新版本。

### Bug description / Bug 描述

When dark theme is enabled in system, first MRepo launch displays white background.

### Expected behavior / 预期行为

<img src=https://github.com/MRepoApp/MRepo/assets/11527277/c05e0627-63dd-41f3-97de-71b5e0c38b3c width=30%>

### Actual behavior / 实际行为

<img src=https://github.com/MRepoApp/MRepo/assets/11527277/8b450203-56e6-4af4-9441-93cb67c1c8bd width=30%>

### Steps to reproduce / 复现步骤

1. Enable dark theme in system
2. Install MRepo and open

### UI / OS

Android

### Android Version / Android 版本

13

**Comment by SanmerDev** [comment]
Fixed in 46c9e3d46f13845504c3f01fec2a104ad29392ac
