### ISSUE TITLE
[Question] Which repos to use/add?

### ISSUE THREAD

**Issue by Bluscream** [MRepoApp/MRepo#118]
Does someome have a links to the repos that i can use with this app? Maybe androidacy and magiskAlt?

**Comment by SanmerDev** [comment]
- [Magisk Modules Alt Repo (mirror)](https://github.com/MRepoApp/magisk-modules-alt-repo)
- [IzzyOnDroid Magisk Repository](https://apt.izzysoft.de/magisk/)

**Comment by Bluscream** [comment]
Thanks a lot!
