### ISSUE TITLE
[FR] MRepo instance list

### ISSUE THREAD

**Issue by Rikj000** [MRepoApp/MRepo#131]
Hi @SanmerDev :wave: 

First of all, thank you for MRepo!   
I really love the private, fair, federated / de-centralized Magisk Modules repo idea,   
even setup my own ([Magisk-Modules-Rikj000-Repo](https://github.com/Rikj000/Magisk-Modules-Rikj000-Repo)) :smile: 

### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of MRepo. / 这个建议不会背离 MRepo 的初衷。

### Enhancement propose / 改进目的

Currently it's hard to find MRepo instances.   

For example,   
only just learned about @IzzySoft's [repo](https://apt.izzysoft.de/magisk/) by digging through closed issues for duplicate FRs before opening this one.
(See https://github.com/MRepoApp/MRepo/issues/118#issuecomment-1803192194)

### Solution / 解决方案

Provide an MRepo instance list,   
which would make it easier for users to find MRepo instances.

Ideally this would:
- Be implemented inside the app, and not in a stand-alone website.
- With some form of auto-detection system in place,   
    to periodically scan Github *(Nice To Have: Gitlab/CodeBerg/Forgejo)* for new MRepo instances.

Auto-detection would be more initial implementation work,   
but will lead to less maintenance work down the road.   

E.g.   
You won't have to deal with PRs to add new MRepo instances to a local list, embedded in the MRepo app.
Instead it would be up to the MRepo maintainers to ensure that their repo's are configured correctly to be auto-detectable.

#### Instance list examples:
- [SearXNG](https://searx.space/#)
- [Invidious](https://redirect.invidious.io/)
- [Lemmy](https://lemmyverse.net/)

**Comment by IzzySoft** [comment]
> With some form of auto-detection system in place

How should that work? Repos are not always hosted at forges. Mine for example is not. Given that useful new repos won't turn up per hour (or even per week at that), it might be much better keeping them in form of a JSON file somewhere. Plus checking/loading that from Github (given @SanmerDev would host it here) should be opt-in, to prevent the need of the `NonFreeNet` anti-feature at F-Droid.

I like the idea of such a feature. First thing would probably be defining what details the list must hold – apart from the Repos' names and URLs. A description should be there outlining what to expect. Some repos might be specific to (a set of) devices, or topics. Some might focus on theming, some on privacy. Some might (like mine) only allowing for FOSS…

Other potential (optional?) candidates for fields might include homepage (for more details), contact info/issue tracker (to reach out to the maintainers), location (country/continent)…

Such a JSON could then also easily be used to create listings on websites – as the instance list examples of your opening comment. But of course this would then mean PRs to get new instances in, existing ones updated, and "goners" removed.

**Comment by Rikj000** [comment]
Hi @IzzySoft,

Thanks for joining the conversation :smile: 

> > With some form of auto-detection system in place
> 
> How should that work? Repos are not always hosted at forges. Mine for example is not. 

You're right about that.   
I gave it some more thought, and checked how Invidious currently does this.

They:
- Request contributors to send PRs to [Github/iv-org/documentation/instances.md](https://github.com/iv-org/documentation/blob/master/docs/instances.md).
- Which is then automatically parsed by [Github/iv-org/instances-api](https://github.com/iv-org/instances-api/) into a publicly hosted [instances.json](https://api.invidious.io/instances.json?pretty=1) file.

Which is similar to what you suggested :slightly_smiling_face: 

Perhaps the linked work of Invidious could be forked and re-used for the MRepo project as well?

**Comment by SanmerDev** [comment]
Not planned, because there is no solution that satisfies me.
