### ISSUE TITLE
Is possible! to add Androidacy magisk-modules-repository??

### ISSUE THREAD

**Issue by arghya339** [MRepoApp/MRepo#142]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of MRepo. / 这个建议不会背离 MRepo 的初衷。

### Enhancement propose / 改进目的

Sir, Is possible to add ?https://www.androidacy.com/magisk-modules-repository/ 

### Solution / 解决方案

NA

### Additional info / 额外信息

NA

**Comment by SanmerDev** [comment]
#28
