### ISSUE TITLE
Submit MRepo to official F-Droid repository

### ISSUE THREAD

**Issue by ClockGen** [MRepoApp/MRepo#152]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of MRepo. / 这个建议不会背离 MRepo 的初衷。

### Enhancement propose / 改进目的

Hello, I'd like to propose to submit MRepo to official F-Droid repository. MRepo is already available in IzzyOnDroid repository, but not in F-Droid official repository. As per F-Droid requirements, I need your permission.

### Solution / 解决方案

I wrote F-Droid metadata https://gitlab.com/fruitsnack/fdroiddata/-/compare/master...mrepo?from_project_id=36528, needed to compile and publish your app. I tested it on my local fdroidserver and it builds fine.  
If you agree, I will open a merge request to include your app to F-Droid.  
Optionally, we can set up reproducible builds (https://f-droid.org/docs/Reproducible_Builds/), so F-Droid will publish your apks signed by you, if they correspond to apks built from this repo.

**Comment by SanmerDev** [comment]
You can add it to F-Droid after updating info below.

- New Translation
```
Translation: https://weblate.sanmer.app/engage/mrepo
```

**Comment by ClockGen** [comment]
@SanmerDev Thanks. However, due to how F-Droid scans repos, it's currently not possible to enable automatic updates or reproducible builds (https://f-droid.org/docs/Reproducible_Builds/), f-droid scanner can't parse versionName and versionCode in app/build.gradle.kts if they're not literal: https://github.com/MRepoApp/MRepo/blob/6471ab6e0bb258e0c167c8785ba4e59f34237118/app/build.gradle.kts#L22
Additionally, with current versionName it's not possible to retrieve APKs published by you (for verification of reproducible build), github release attachments can be retrieved from an url like `https://github.com/MRepoApp/MRepo/releases/download/v%v/app-release.apk`, F-Droid can substitute parts of the url with versionCode and versionName. In this case, we can substitute `%v` with versionName, so it will become `v2.4.3` and match the release tag.  
As you can see, it's not possible with current `2.4.3.5e1e788` versionName.

Can you please set versionName to be without `5e1e788` commit hash suffix and versionCode to be literal, so they'd look like:
```
        versionName = "2.4.3"
        versionCode = 677
```
in `app/build.gradle.kts`.

Alternatively, it's possible to keep these values as functions, and instead attach a new text file to new releases that will contain expected versionName and versionCode, for example:  
`version.txt`
```
versionName=2.4.3
versionCode=677
```
However, in this case, it's still required to remove the `5e1e788` commit hash suffix from versionName.

**Comment by SanmerDev** [comment]
I want to keep the commit hash suffix, so is it okay to add a `version_code.txt` like [LibChecker 2.4.4](https://github.com/LibChecker/LibChecker/releases/tag/2.4.4) ?

**Comment by ClockGen** [comment]
> I want to keep the commit hash suffix, so is it okay to add a `version_code.txt` like [LibChecker 2.4.4](https://github.com/LibChecker/LibChecker/releases/tag/2.4.4) ?

Yes, but in this case reproducible builds wont be enabled (libchecker doesn't have it), so apk will be signed with f-droid key instead.

**Comment by SanmerDev** [comment]
Is it feasible to only modify the naming rules of the APK file?

**Comment by ClockGen** [comment]
No, because this pattern can't be used in github release link, if it was just "2.4.3" we could replace `%v` in this link `https://github.com/MRepoApp/MRepo/releases/download/v%v/app-release.apk` with versionName (unfortunately f-droid can only replace versionCode and versionName in upstreak APK links) and it would match. This is needed for f-droid to retrieve your APK (which is then compared to what's been built at f-droid, and if they match, your apk is published, otherwise f-droid just publishes the built apk). Reproducible builds are only recommended though, so if you don't want to modify your versioning scheme, the solution like libchecker uses is fine.

**Comment by SanmerDev** [comment]
So I need to change the APK file name to `app-release.apk`? 
It is possible to change the APK file name, but the `versionName` inside the APP will not be changed.

**Comment by ClockGen** [comment]
No, APK name can retain same naming scheme, which is `MRepo-versionName-versionCode-release.apk`, assuming that you will change versionName to remove the hash suffix. 

During the stage, when F-droid downloads the apk, there's only two values that can be used in APK link: versionCode (`%c`) and versionName (`%v`), which can either be specified in a separate file or f-droid scans them directly in app/build.gradle.kts.

Github release permalinks look like this:
`https://github.com/MRepoApp/MRepo/releases/download/v2.4.3/MRepo-2.4.3.5e1e788-677-release.apk`, but F-Droid must also reuse this link for all future versions, in this case we can we can substitute parts of the link like this:
`https://github.com/MRepoApp/MRepo/releases/download/v%v/MRepo-%v-%c-release.apk`.   

If versionName is just `2.4.3`, then the git tag in this link gets correctly replaced as `v2.4.3`, not as `v2.4.3.5e1e788` (which doesn't exist).

And, if you'd provide versionName="2.4.3" in version.txt but the actual app would have 2.4.3.5e1e788, f-droid checks expected and actual versionCodes after building, so it'd fail.  

Unfortunately it's the only way to get both auto-updates and reproducible builds going.

**Comment by SanmerDev** [comment]
Providing `version.txt` is indeed the most appropriate way. 🤔

Already added [version_code.txt](https://github.com/MRepoApp/MRepo/releases/download/v2.4.3/version_code.txt) in latest release.

**Comment by ClockGen** [comment]
No reproducible builds then?

**Comment by SanmerDev** [comment]
> No reproducible builds then?

There is a similar issue in LibChecker, I will follow their decision 😶‍🌫️.

**Comment by ClockGen** [comment]
I fixed translation link, enabled automatic updates and opened a MR: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14433

**Comment by ClockGen** [comment]
MRepo was merged in fdroiddata and will be available in F-Droid soon (may take up to a week) https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client.

**Comment by shuvashish76** [comment]
Live on F-Droid : https://f-droid.org/packages/com.sanmer.mrepo/
Feel free to use their badge: https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md
