### ISSUE TITLE
[FR] APatch support

### ISSUE THREAD

**Issue by melontini** [MRepoApp/MRepo#162]
### Checklist

- [X] No one has submitted a similar or identical feature request before
- [X] This suggestion does not depart from the original intention of MRepo

### Enhancement propose

APatch is a new KSU-like framework for patching the Android kernel and system. https://github.com/bmax121/APatch

Currently, MRepo just crashes after granting it root access.

### Additional info

Thank you for your great work, the app is incredible!

**Comment by SanmerDev** [comment]
Can you try it? [MRepo-2.4.3.dev.0462dbe-710-debug.apk.zip](https://github.com/MRepoApp/MRepo/files/14240229/MRepo-2.4.3.dev.0462dbe-710-debug.apk.zip)

**Comment by melontini** [comment]
Yes, it works! But I also caught a crash after hitting the end of a module's page. 
[crash.log](https://github.com/MRepoApp/MRepo/files/14240571/crash.log)

**Comment by SanmerDev** [comment]
Thanks, the crash came from another issue, I'll check further.
