### ISSUE TITLE
[FR] FAB That takes you back to the top of repository tab

### ISSUE THREAD

**Issue by Wojtaz0w** [MRepoApp/MRepo#177]
### Checklist

- [X] No one has submitted a similar or identical feature request before
- [X] This suggestion does not depart from the original intention of MRepo

### Enhancement propose

I believe it would be very convenient to have this feature, especially based on the fact that a single repo (Magisk-Modules-Alt-Repo) already has 96 modules.

### Solution

In a similar matter to FAB in "Modules" which lets you choose a ZIP file to install a module from.
Its appearance condition would need to be changed, instead of hiding after scrolling down, make it appear after scrolling down the list.

### Additional info

Here is a mock-up I drew.
![Screenshot_20240310-152924_MRepo](https://github.com/MRepoApp/MRepo/assets/104674625/9424ad9a-2c67-40b9-bf72-b9ed79dc3343)

**Comment by SanmerDev** [comment]
I don't like this, there is already a `Scrollbar` so no need for a `FAB`

**Comment by Wojtaz0w** [comment]
Scrollbar often collides with Android system gestures, that's why for me an FAB would have been more convenient. But it is up to you whether you'll implement it.
