### ISSUE TITLE
Cannot add any repo, no matter what.

### ISSUE THREAD

**Issue by webmaster-exit-1** [MRepoApp/MRepo#189]
### Checklist

- [X] No one has submitted a similar or identical bug report before
- [X] I'm using the latest version of MRepo

### Bug description

no matter how i try to enter a url, it complains that they are either wrong or the app wants repo's to end with :/ which makes no Fing sense. None.

### Expected behavior

For a repo of modules to be added, like how easy it is on F-droid. But noooo. This f-ing app...

### Actual behavior

bullshit, poorly programmed. probably no ci jobs to automate all this for the dev.

### Steps to reproduce

try add any f-ing repo

### UI / OS

OnePlus Nord N30 5G

### Android Version

14

### Additional info

You can add module repo's. How? beats me. It wants repo urls to end in ":/" which make ZERO f**king sense! 
![Screenshot_2024-03-28-07-36-56-34_49d88847ecc10b226c73e47576f4ed73](https://github.com/MRepoApp/MRepo/assets/98633966/eda3ebc9-e6dc-4716-a4e0-5f12c210b83f)
![Screenshot_2024-03-28-07-37-03-56_49d88847ecc10b226c73e47576f4ed73](https://github.com/MRepoApp/MRepo/assets/98633966/ebeeab4f-1a0e-4284-924b-e9a9a38b594a)

**Comment by webmaster-exit-1** [comment]
URL'S DO NOT FUCKING END IN :/

**Comment by SanmerDev** [comment]
Xposed-Modules-Repo is not supported

**Comment by webmaster-exit-1** [comment]
So a magisk module repo doesn't support magisk module repo url....
Right....
