### ISSUE TITLE
[FR] Label for "Reboot" button

### ISSUE THREAD

**Issue by MisterFloppy** [MRepoApp/MRepo#191]
### Checklist

- [X] No one has submitted a similar or identical feature request before
- [X] This suggestion does not depart from the original intention of MRepo

### Enhancement propose

When a module has been updated through MRepo and a reboot is required, there is only an unlabeled button popping up. I would like to intercept this moment with Tasker and its plugin AutoInput, but I can't because this app needs some text to react to.

### Solution

Could you please add an useful label named "Reboot" or so to this button?

**Comment by SanmerDev** [comment]
I don't understand your needs, but if you want to know whether any modules have been updated, you can scan whether there is an update file under `/data/adb/modules/<ID>`

**Comment by SanmerDev** [comment]
I don't understand your needs, but if you want to know whether any modules have been updated, you can scan whether there is an update file under `/data/adb/modules/<ID>`

**Comment by MisterFloppy** [comment]
![Screenshot_2024-03-29-14-33-35-585_com sanmer mrepo](https://github.com/MRepoApp/MRepo/assets/6067839/2929ca51-e9f4-40b3-ad71-4bfbc58e1d3f)
![Screenshot_2024-03-29-14-41-28-105_com sanmer mrepo](https://github.com/MRepoApp/MRepo/assets/6067839/bb48efa5-4bc5-4aa7-8f28-074981aa3181)

After I have clicked the "Update" button (first screenshot), the update process begins and finally looks like the second screenshot. Then a little button appears at the bottom right position indicating a reboot is required.

I don't want to reboot straight away, but let the app "Tasker" automatically recognize that the update process has ended. However, Tasker must "see" some text on the screen it can react to, so it would be great if you could add something like "Reboot" to the reboot button.

**Comment by MisterFloppy** [comment]
What do you mean with "subtitle"? Is it an option in MRepo? Or an Android setting? Or a Magisk module? Sorry, I'm absolutelyl clueless...

**Comment by MisterFloppy** [comment]
This is how it looks when you install a module from zip archive through Magisk. Tasker can detect the completed installation by recognizing the word "Neustart". This way it can programatically take some precautionary measures before the actual reboot happens.

![Screenshot_2024-03-29-22-52-46-025_com topjohnwu magisk](https://github.com/MRepoApp/MRepo/assets/6067839/92414996-a651-4680-b595-159dce5b6aef)

**Comment by MisterFloppy** [comment]
Ahhhh... I must have been blind :-)
I didn't see that the text right after the completed installation on the top has changed to "Fertig!".

Okay, thank you - case closed.
