### ISSUE TITLE
[BUG] App lost root permissions 

### ISSUE THREAD

**Issue by vulcanrvn90** [MRepoApp/MRepo#194]
### Checklist

- [X] No one has submitted a similar or identical bug report before
- [X] I'm using the latest version of MRepo

### Bug description

After updating to the latest version, I realized my mrepo has lost its root permissions. Under the settings screen it shows Root Access: None Provider: Not Available. Also when checking magisk delta, mrepo is no longer showing on the superuser list. 

### Expected behavior

After updating the app work as normal.

### Actual behavior

Unable to install, remove or update modules.

### Steps to reproduce

1. Open the app
2. ?

### UI / OS

Asus

### Android Version

12

### Additional info

I have uninstalled the app, reinstalled with the latest version as well as the two previous versions which worked just fine before this issue.

**Comment by SanmerDev** [comment]
This is not caused by MRepo, because this has never happened in KernelSU/Magisk/Magisk Alpha.
