### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by bphd** [MRepoApp/MRepo#197]
### Checklist

- [X] No one has submitted a similar or identical bug report before
- [X] I'm using the latest version of MRepo

### Bug description

04-05 12:03:11.320 12352 12352 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
04-05 12:03:11.320 12352 12352 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
04-05 12:03:11.348 12352 12370 I AdrenoGLES-0: QUALCOMM build                   : cac6e6f805, I5187d04b75
04-05 12:03:11.348 12352 12370 I AdrenoGLES-0: Build Date                       : 11/22/21
04-05 12:03:11.348 12352 12370 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.35.01.10
04-05 12:03:11.348 12352 12370 I AdrenoGLES-0: Local Branch                     : 
04-05 12:03:11.348 12352 12370 I AdrenoGLES-0: Remote Branch                    : 
04-05 12:03:11.348 12352 12370 I AdrenoGLES-0: Remote Branch                    : 
04-05 12:03:11.348 12352 12370 I AdrenoGLES-0: Reconstruct Branch               : 
04-05 12:03:11.348 12352 12370 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
04-05 12:03:11.348 12352 12370 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
04-05 12:03:11.378 12352 12370 I AdrenoGLES-0: PFP: 0x016dc094, ME: 0x00000000
04-05 12:03:16.675 12352 12361 W om.sanmer.mrepo: Reducing the number of considered missed Gc histogram windows from 214 to 100
04-05 12:03:16.677 12352 12363 W System  : A resource failed to call close. 
04-05 12:03:19.328 12352 12363 W System  : A resource failed to call close. 
04-05 12:03:19.328 12352 12363 W System  : A resource failed to call close. 
04-05 12:03:19.328 12352 12363 W System  : A resource failed to call close. 
04-05 12:03:19.329 12352 12363 W System  : A resource failed to call close. 
04-05 12:03:23.248 12352 12352 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
04-05 12:03:23.248 12352 12352 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
04-05 12:03:23.257 12352 12352 D Compose Focus: Owner FocusChanged(true)
04-05 12:03:23.266 12352 12352 I ImeTracker: com.sanmer.mrepo:3fa3357c: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT_BY_INSETS_API
04-05 12:03:23.266 12352 12352 D InsetsController: show(ime(), fromIme=false)
04-05 12:03:23.266 12352 12352 D InputMethodManager: showSoftInput() view=com.sanmer.mrepo.t3{9fec63f VFED..... .F....I. 0,0-1080,2400 aid=1073741832} flags=0 reason=SHOW_SOFT_INPUT_BY_INSETS_API
04-05 12:03:23.299 12352 12352 D InsetsController: show(ime(), fromIme=true)
04-05 12:03:23.386 12352 12363 W System  : A resource failed to call release. 
04-05 12:03:23.598 12352 12352 I ImeTracker: com.sanmer.mrepo:3fa3357c: onShown
04-05 12:04:09.478 12352 12352 D <MR_REL>uJ: ModuleViewModel init: Fdroid-Priv
04-05 12:04:09.482 12352 12352 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
04-05 12:04:09.482 12352 12352 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
04-05 12:04:09.868 12352 12352 I ImeTracker: com.sanmer.mrepo:1dc455b1: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
04-05 12:04:09.869 12352 12352 I ImeTracker: com.sanmer.mrepo:8e2aca10: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
04-05 12:04:09.887 12352 12352 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@116376430 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@33cc235
04-05 12:04:09.888 12352 12352 I ImeTracker: com.sanmer.mrepo:8e2aca10: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
04-05 12:04:10.173 12352 12352 I ImeTracker: com.sanmer.mrepo:d8bfdba2: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
04-05 12:04:10.173 12352 12352 I ImeTracker: com.sanmer.mrepo:1dc455b1: onHidden
04-05 12:04:12.285 12352 12352 D <MR_REL>DownloadService: DownloadService onCreate
04-05 12:04:12.326 12352 12352 W DocumentFile: Failed to createFile: java.io.IOException: No such file or directory
04-05 12:04:22.290 12352 12352 D <MR_REL>DownloadService: DownloadService onDestroy
04-05 12:04:22.930 12352 12352 D <MR_REL>DownloadService: DownloadService onCreate
04-05 12:04:22.942 12352 12352 W DocumentFile: Failed to createFile: java.io.IOException: No such file or directory
04-05 12:04:26.405 12352 12352 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
04-05 12:04:26.405 12352 12352 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
04-05 12:04:28.100 12352 12352 W DocumentFile: Failed to createFile: java.io.IOException: No such file or directory
04-05 12:04:28.103 12352 12352 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@5d0fd1e
04-05 12:04:28.105 12352 12370 D OpenGLRenderer: endAllActiveAnimators on 0xb4000076ad4cbe00 (kh0) with handle 0xb40000770af43940
04-05 12:04:29.327 12352 12352 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
04-05 12:04:29.327 12352 12352 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
04-05 12:04:29.903 12352 12352 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@cd80212
04-05 12:04:29.907 12352 12370 D OpenGLRenderer: endAllActiveAnimators on 0xb400007698462600 (kh0) with handle 0xb4000076ad24a840
04-05 12:04:29.923 12352 12352 W DocumentFile: Failed to createFile: java.io.IOException: No such file or directory
04-05 12:04:32.933 12352 12352 D <MR_REL>DownloadService: DownloadService onDestroy
04-05 12:04:36.365 12352 12352 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
04-05 12:04:36.365 12352 12352 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
04-05 12:04:36.378 12352 12352 I ImeTracker: com.sanmer.mrepo:58aa19cb: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT_BY_INSETS_API
04-05 12:04:36.378 12352 12352 D InsetsController: show(ime(), fromIme=false)
04-05 12:04:36.378 12352 12352 D InputMethodManager: showSoftInput() view=com.sanmer.mrepo.t3{9fec63f VFED..... .F....I. 0,0-1080,2400 aid=1073741832} flags=0 reason=SHOW_SOFT_INPUT_BY_INSETS_API
04-05 12:04:36.404 12352 12352 D InsetsController: show(ime(), fromIme=true)
04-05 12:04:36.496 12352 12363 W System  : A resource failed to call release. 
04-05 12:04:36.704 12352 12352 I ImeTracker: com.sanmer.mrepo:58aa19cb: onShown
04-05 12:04:40.463 12352 12352 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@116376430 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@d859f01
04-05 12:04:40.770 12352 12352 I ImeTracker: com.sanmer.mrepo:e9fcb45b: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
04-05 12:04:40.770 12352 12352 I ImeTracker: com.sanmer.mrepo:3fa90733: onHidden
04-05 12:04:45.269 12352 12352 D <MR_REL>uJ: ModuleViewModel init: adrianmmiller.KSUdebloat
04-05 12:04:45.271 12352 12352 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
04-05 12:04:45.271 12352 12352 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
04-05 12:04:45.636 12352 12352 I ImeTracker: com.sanmer.mrepo:8d27c8bd: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
04-05 12:04:45.637 12352 12352 I ImeTracker: com.sanmer.mrepo:cf93495b: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
04-05 12:04:45.637 12352 12352 I ImeTracker: com.sanmer.mrepo:cf93495b: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
04-05 12:04:58.422 12352 12352 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
04-05 12:04:58.422 12352 12352 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
04-05 12:04:58.431 12352 12352 I ImeTracker: com.sanmer.mrepo:5e91d6c5: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT_BY_INSETS_API
04-05 12:04:58.431 12352 12352 D InsetsController: show(ime(), fromIme=false)
04-05 12:04:58.432 12352 12352 D InputMethodManager: showSoftInput() view=com.sanmer.mrepo.t3{9fec63f VFED..... .F....I. 0,0-1080,2400 aid=1073741832} flags=0 reason=SHOW_SOFT_INPUT_BY_INSETS_API
04-05 12:04:58.458 12352 12352 D InsetsController: show(ime(), fromIme=true)
04-05 12:04:58.505 12352 12363 W System  : A resource failed to call release. 
04-05 12:04:58.761 12352 12352 I ImeTracker: com.sanmer.mrepo:5e91d6c5: onShown
04-05 12:05:01.883 12352 12352 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@116376430 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@95ce964
04-05 12:05:02.189 12352 12352 I ImeTracker: com.sanmer.mrepo:96c3976d: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
04-05 12:05:02.190 12352 12352 I ImeTracker: com.sanmer.mrepo:ba0d5084: onHidden
04-05 12:05:12.716 12352 12352 D <MR_REL>uJ: ModuleViewModel init: systemless-hosts-KernelSU-module
04-05 12:05:12.717 12352 12352 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
04-05 12:05:12.717 12352 12352 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
04-05 12:05:13.074 12352 12352 I ImeTracker: com.sanmer.mrepo:7c0a5075: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
04-05 12:05:13.075 12352 12352 I ImeTracker: com.sanmer.mrepo:84284086: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
04-05 12:05:13.075 12352 12352 I ImeTracker: com.sanmer.mrepo:84284086: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
04-05 12:05:18.679 12352 12352 D <MR_REL>DownloadService: DownloadService onCreate
04-05 12:05:18.687 12352 12352 W DocumentFile: Failed to createFile: java.io.IOException: No such file or directory
04-05 12:05:27.476 12352 12352 D <MR_REL>kK: ModulesViewModel init
04-05 12:05:28.683 12352 12352 D <MR_REL>DownloadService: DownloadService onDestroy
04-05 12:05:29.124 12352 12352 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
04-05 12:05:29.124 12352 12352 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.

### Expected behavior

A

### Actual behavior

A

### UI / OS

a

### Android Version

a

**Comment by SanmerDev** [comment]
Too little info

**Comment by bphd** [comment]
> Too little info

Tons of logs but too little info?

**Comment by lihenggui** [comment]
> > Too little info
> 
> Tons of logs but too little info?

You didn't specify which error or bug you encountered. Only the log itself is not useful.

At least you should include the bug description and steps to reproduce.
---
**Description:**
A clear and concise description of what the bug is.

**Steps to Reproduce:**

Go to '...'
Click on '....'
Scroll down to '....'
See error

**Environment:**

OS: [e.g. Android 14]
Version [e.g. 22]

OS: [e.g. Windows, MacOS, Linux]
Browser [e.g. Chrome, Safari]
Version [e.g. 22]
---

**Comment by bphd** [comment]
> > > Too little info
> > 
> > 
> > Tons of logs but too little info?
> 
> You didn't specify which error or bug you encountered. Only the log itself is not useful.
> 
> At least you should include the bug description and steps to reproduce.
> 
 **Description:** A clear and concise description of what the bug is. : Crash
> 
 **Steps to Reproduce:** : Open app
> 
 Go to '...' Click on '....' Scroll down to '....' See error : See logs
> 
 **Environment:** : Android
> 
 OS: [e.g. Android 14] Version [e.g. 22] : Android 14, latest

**Comment by lihenggui** [comment]
There is no crash stack info on the log you attached. You can upload the entire log file instead of just a portion.

**Comment by bphd** [comment]
> There is no crash stack info on the log you attached. You can upload the entire log file instead of just a portion.

I don't have it anymore but normaly reelvant informations about the problem are there
