### ISSUE TITLE
[BUG] 404 Not Found

### ISSUE THREAD

**Issue by Ivy-Tokito** [MRepoApp/MRepo#199]
### Checklist

- [X] No one has submitted a similar or identical bug report before
- [X] I'm using the latest version of MRepo

### Bug description

Unable to add my custom module repo
[MRepo_2024-04-09T20_45_02.800237.log](https://github.com/MRepoApp/MRepo/files/14920706/MRepo_2024-04-09T20_45_02.800237.log)
- `ivy-tokito.github.io/module-repo` the page is active and opens in browser
- I was able to add other repos like [izzysoft](https://apt.izzysoft.de/magisk/) & [Rikj000](https://Rikj000.github.io/Magisk-Modules-Rikj000-Repo/) Repo

### Expected behavior

Adds my repo to Repository list

### Actual behavior

404 not found exception

### Steps to reproduce

1 Got repository settings 
2 Try adding my repo `ivy-tokito.github.io/module-repo` 

### UI / OS

VoltageOS 3.2 Unofficial + Nexus Kernelsu 

### Android Version

14

### Additional info

**Please let me know if i am doing something wrong!**

**Comment by SanmerDev** [comment]
You can refer to [demo](https://github.com/MRepoApp/demo-modules-repo).

**Comment by Ivy-Tokito** [comment]
i figured it out i was not creating index i.e `module.json` 
- one  issue `"added": null,`  returns error in app expected double 
- Is this a bug or am i doing something wrong again!
  - I am just putting random number as a workaround

**Commands Used**
```console
$ python utils/cli.py track --stdin << EOF
{
  "id": "safetynet-fix",
  "enable": true,
  "update_to": "https://raw.githubusercontent.com/kdrag0n/safetynet-fix/master/update.json",
  "license": "GPL-3.0",
  "homepage": "https://kdrag0n.dev/",
  "source": "https://github.com/kdrag0n/safetynet-fix.git",
  "support": "https://github.com/kdrag0n/safetynet-fix/issues",
}
EOF
$ python utils/cli.py sync
$ python utils/cli.py index
```

**track.json**
```
{
  "id": "safetynet-fix",
  "enable": true,
  "update_to": "https://raw.githubusercontent.com/kdrag0n/safetynet-fix/master/update.json",
  "license": "GPL-3.0",
  "homepage": "https://kdrag0n.dev/",
  "source": "https://github.com/kdrag0n/safetynet-fix.git",
  "support": "https://github.com/kdrag0n/safetynet-fix/issues",
  "last_update": 1673286512.0,
  "versions": 1
}
```

**module.json**
```
{
  "name": "Module Repo",
  "metadata": {
    "version": 1,
    "timestamp": 1712809244.502989
  },
  "modules": [
    {
      "id": "safetynet-fix",
      "name": "Universal SafetyNet Fix",
      "version": "v2.4.0",
      "versionCode": 20400,
      "author": "kdrag0n",
      "description": "A universal fix for SafetyNet and Play Integrity on Android 8\u201313 devices with hardware attestation.",
      "track": {
        "type": "ONLINE_JSON",
        "added": null,
        "license": "GPL-3.0",
        "homepage": "https://kdrag0n.dev/",
        "source": "https://github.com/kdrag0n/safetynet-fix.git",
        "support": "https://github.com/kdrag0n/safetynet-fix/issues",
        "donate": ""
      },
      "versions": [
        {
          "timestamp": 1673286512.0,
          "version": "v2.4.0",
          "versionCode": 20400,
          "zipUrl": "https://ivy-tokito.github.io/module-repo/modules/safetynet-fix/v2.4.0_20400.zip",
          "changelog": "https://ivy-tokito.github.io/module-repo/modules/safetynet-fix/v2.4.0_20400.md"
        }
      ]
    }
  ]
}
```
**log**
```
[2024/04/11 09:15:42] LocalTracks INFO: get_tracks: modules_folder = /path/module-repo/modules
[2024/04/11 09:15:42] LocalTracks INFO: get_tracks: size = 1
[2024/04/11 09:15:42] Pull DEBUG: from_track: [safetynet-fix] -> type: ONLINE_JSON
[2024/04/11 09:15:45] Sync INFO: update: [safetynet-fix] -> update to v2.4.0 (20400)
```

**Comment by SanmerDev** [comment]
> one issue "added": null, returns error in app expected double

Fixed: https://github.com/MRepoApp/magisk-modules-repo-util/commit/b5cea1b6a385adc1d7daa051f2032f780b7dc52b

**Comment by Ivy-Tokito** [comment]
Great!
