### ISSUE TITLE
[FR] Fastlane i18n

### ISSUE THREAD

**Issue by yurtpage** [MRepoApp/MRepo#212]
### Checklist

- [X] No one has submitted a similar or identical feature request before
- [X] This suggestion does not depart from the original intention of MRepo

### Enhancement propose

Please add a Weblate component to translate Fastline metadata here
https://weblate.sanmer.app/projects/mrepo/

### Solution

You may check Conversations app how they did it

**Comment by SanmerDev** [comment]
Added: https://weblate.sanmer.app/projects/mrepo/fastlane/
