### ISSUE TITLE
[FR] Add a confirmation prompt when installing a module from intent

### ISSUE THREAD

**Issue by 821938089** [MRepoApp/MRepo#218]
### Checklist

- [X] No one has submitted a similar or identical feature request before
- [X] This suggestion does not depart from the original intention of MRepo

### Enhancement propose

Add a confirmation prompt when installing a module from intent

### Solution

A page pops up with a description of the module to be installed, alerting to security risks.

**Comment by SanmerDev** [comment]
I think this is redundant. You should check contents of the zipfile (include scripts) before you decide to install it.

> This is the best way to ensure security. And if you can’t read scripts, learn it.
