### ISSUE TITLE
[BUG] Repository contents are not updated

### ISSUE THREAD

**Issue by anyuta1166** [MRepoApp/MRepo#243]
### Checklist

- [X] No one has submitted a similar or identical bug report before
- [X] I'm using the latest version of MRepo

### Bug description

Repository content is not updated on application start and on swipe down.

### Expected behavior

Repository content should be updated on application start and on swipe down.

### Actual behavior

Repository content is not updated on application start and on swipe down.

### UI / OS

MIUI

### Android Version

11

### Additional info

Repository content is not updated on application start and on swipe down.
The only way to update the repository content is to go to Settings - Repositories and press the Update button.
Last working version - 2.4.8.
Broken since - 2.4.9.

**Comment by SanmerDev** [comment]
- Pull to refresh: removed
- Update content at startup: fixed
