### ISSUE TITLE
[BUG] URL in magisk-alt-repo returns error

### ISSUE THREAD

**Issue by Chaprnks** [MRepoApp/MRepo#249]
### Checklist

- [X] No one has submitted a similar or identical bug report before
- [X] I'm using the latest version of MRepo

## Use in MRepo
```
https://raw.githubusercontent.com/MRepoApp/magisk-modules-alt-repo/main/
```

### Expected behavior

Similar page to what the demo repository shows

![wXJn0eZ - Imgur](https://github.com/MRepoApp/MRepo/assets/6340970/85df914f-6d32-436c-9496-f3d617ed7147)

### Actual behavior

`400: Invalid request`

![invalidrequest](https://github.com/MRepoApp/magisk-modules-alt-repo/assets/6340970/eb6d8b58-a215-42e8-9ce6-25e4499dcd83)

### Steps to reproduce

1. Open https://github.com/MRepoApp/magisk-modules-alt-repo
2. Copy link in readme.md
3. Paste link to address bar

**Comment by Chaprnks** [comment]
I read through the closed issue posts & found the correct URL for adding the repository. Unfortunately that doesn't work either.

http://alt-repo.sanmer.app/
![ag8XF5o - Imgur](https://github.com/MRepoApp/MRepo/assets/6340970/5c54f9d4-e75e-4268-9a9e-aebc80094189)

# Adding alt repo to MRepo app
![alt-repo1](https://github.com/MRepoApp/MRepo/assets/6340970/19ae7c9a-efa9-4b42-80e1-136a26d6d7c9)
![alt-repo2](https://github.com/MRepoApp/MRepo/assets/6340970/3d00cf7a-52f7-4894-b2c1-0e133688b472)


# Adding izzysoft repo to MRepo app
![izzy-repo1](https://github.com/MRepoApp/MRepo/assets/6340970/dad71e66-5deb-4d8d-8a34-39f1a23d69bc)
![izzy-repo2](https://github.com/MRepoApp/MRepo/assets/6340970/256fb5ac-54ff-402f-8c79-e3bb9a9240c7)

**Comment by SanmerDev** [comment]
Some module's changelog can't be compiled by GitHub Pages, So only the raw url is available.

**Comment by Chaprnks** [comment]
Is there any way to get the alt repo working with MRepo? Even if I have to compile, run & host it myself

**Comment by SanmerDev** [comment]
Why don't you use this???
```
https://raw.githubusercontent.com/MRepoApp/magisk-modules-alt-repo/main/
```

**Comment by Chaprnks** [comment]
> Is there any way to get the alt repo working with MRepo? Even if I have to compile, run & host it myself

because it shows an error code & doesn't work.

400: invalid request
